name: Node.js CI

on:
  push:
    branches: [ stage ]
  pull_request:
    branches: [ stage ]

env:
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  MONGODB_URI_TESTS: ${{ secrets.MONGODB_URI_TESTS }}

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Create env file
        run: |
          touch .env
          echo JWT_SECRET =${{ secrets.JWT_SECRET }} >> .env
          echo MONGODB_URI_TESTS =${{ secrets.MONGODB_URI_TESTS }} >> .env
      - name: Test @workout-assitant/server
        run: yarn workspace @workout-assitant/server test:ci