name: Node.js CI

on:
  push:
    branches: [ stage ]
  pull_request:
    branches: [ stage ]

env:
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  MONGODB_URI_TESTS: ${{ secrets.MONGODB_URI_TESTS }}

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Create env file
        run: |
          touch packages/server/.env
          echo JWT_SECRET =$JWT_SECRET >> packages/server/.env
          echo MONGODB_URI_TESTS =$MONGODB_URI_TESTS >> packages/server/.env
          cat packages/server/.env
      - name: Test @workout-assitant/server
        run: yarn workspace @workout-assitant/server test:ci